env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/no-unresolved: off
  import/prefer-default-export: off
  react/jsx-filename-extension: off
  react/jsx-tag-spacing: off
  arrow-body-style: off
  no-param-reassign: off
  no-use-before-define: off
  no-unused-vars: off
  no-undef-init: off
  object-curly-newline: off
  no-shadow: off
  arrow-parens: off
  react/prop-types: off
  react/no-array-index-key: off
  no-bitwise: off
  class-methods-use-this: off
  no-return-await: off
  no-lonely-if: off
  no-underscore-dangle: off
  react/jsx-one-expression-per-line: off
  max-len: off
